### ISSUE TITLE
Error while converting to a pth file

### ISSUE THREAD

**Issue by faaizhashmi** [husthuaan/AoANet#12]
Hi there. I am now trying to train the model on Flickr30k. but when i run the script

```
import numpy as np
import os
import torch
from tqdm import tqdm

out = {}
def transform(id_file, feat_file):
  ids = open(id_file, 'r').readlines()
  ids = [_.strip('\n') for _ in ids]
  feats = np.load(feat_file)
  assert feats.shape[0] == len(ids)
  for _id, _feat in tqdm(zip(ids, feats)):
    out[str(_id)] = _feat

transform('dev_ids.txt', 'dev_ims.npy')
transform('train_ids.txt', 'train_ims.npy')
transform('test_ids.txt', 'test_ims.npy')

torch.save(out, 'f30kbu_att.pth')
```

i got this error
```

5070it [00:00, 1866343.80it/s]
Traceback (most recent call last):
  File "scripts/convert_to_pth.py", line 16, in <module>
    transform('/home/faaiz/Downloads/AoANet-master(flickr)/scripts/train_ids.txt', '/home/faaiz/Downloads/AoANet-master(flickr)/scripts/train_ims.npy')
  File "scripts/convert_to_pth.py", line 10, in transform
    feats = np.load(feat_file)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 712, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
MemoryError
*** Reference count error detected: 
an attempt was made to deallocate 11 (f) ***
```

**Comment by hishamabutt** [comment]
@husthuaan features like cooc_att, coco_fc and coco_box?
and can you tell me how can i train the model on both flickr30k and coco data set? can it be done with the model i have already trained on coco data set? or i have to train the model again using?

**Comment by husthuaan** [comment]
@hishamabutt If you want train the two datasets together (we ususally don't do this), you should merge `dataset_coco.json` and `dataset_flickr30k.json` to a new json file and also merge the features.
I think you'd better process the merged dataset and train the model again, for the vocabulary is different.
