### ISSUE TITLE
Terminating BlobFetcher

### ISSUE THREAD

**Issue by AlanChangre** [husthuaan/AoANet#57]
When i was training, it appeared Terminating BlobFetcher and stoped every time when the iter reached 283214, I didn't change anything in the code.
![QQ截图20220105142828](https://user-images.githubusercontent.com/41631703/148171085-95cd94d8-cdad-4e55-b31c-82a2f4c15427.jpg)
828.jpg…]()

**Comment by zxh19976666** [comment]
when i run train.sh it show me :

tensorboardX is not installed
DataLoader loading json file: data/cocotalk.json
vocab size is 9487
DataLoader loading h5 file: data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
File "train.py", line 275, in
train(opt)
File "train.py", line 52, in train
with open(os.path.join(opt.start_from, 'infos_'+opt.id+'.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'log/log_aoanet/infos_aoanet.pkl'
Terminating BlobFetcher

where is 'log/log_aoanet/infos_aoanet.pkl'？

**Comment by hwbhwbgao** [comment]
> 

你这是训练不是在使用SCST进行优化，将start_from置为None

**Comment by zxh19976666** [comment]
> > 
> 
> 你这是训练不是在使用SCST进行优化，将start_from置为None

老哥能加个QQ吗，问一下这个代码的事

**Comment by akay232** [comment]
I found this google drive page may be this is the required file you are looking for 
[https://drive.google.com/drive/folders/1skbcKpD5TMDlqZUT_97eDzoSZyJShZEm](url)

**Comment by zxh19976666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
